# https://github.com/line/lich/blob/master/.github/workflows/ossrh.yml

name: Deploy to OSSRH

on:
  workflow_dispatch:
    inputs:
      cond_release:
        description: 'Type "release" to release artifacts to Maven Central.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Deploy artifacts
        env:
          ORG_GRADLE_PROJECT_repositoryUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_repositoryPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish --stacktrace
      - name: Release to Maven Central
        if: ${{ github.event.inputs.cond_release == 'release' }}
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew closeAndReleaseRepository --stacktrace

