# https://github.com/line/lich/blob/master/.github/workflows/ossrh.yml

name: Deploy To OSSRH And Release With Tag

on:
  workflow_dispatch:
    inputs:
      cond_release:
        description: 'Type "release" to release artifacts to Maven Central.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish and close repository
        if: ${{ github.event.inputs.cond_release == 'release' }}
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish closeAndReleaseSonatypeStagingRepository --stacktrace

  tag_and_release:
    name: Create Tag And Release
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Retrieve Version
        run: |
          echo "version_name=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_OUTPUT
        id: sdk_version

      - name: Get Version
        run: |
          echo "version_name=${{steps.sdk_version.outputs.VERSION_NAME}}"

      - name: Create Tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: "v${{steps.sdk_version.outputs.VERSION_NAME}}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{steps.sdk_version.outputs.VERSION_NAME}}"
          release_name: "Release ${{steps.sdk_version.outputs.VERSION_NAME}}"
          draft: false
          prerelease: false